

all:
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."
cliente_configurable:
	@echo "Ejecutando con socket configurable..."
	python3 cli4.py $(socket_path)
servidor_configurable:
	@echo "Ejecutando con socket configurable..."
	python3 serv4.py $(socket_path)
