

all:
	@echo "Compilación y ejecución de la práctica"
	

cliente: cliente.py
	@echo "Compilando y ejecutando cliente y servidor..."
	python3 cliente.py

servidor: servidor.py
	@echo "Compilando y ejecutando cliente y servidor..."
	python3 servidor.py

ejecutar:
	python3 cliserv2.py

clean:
	@echo "Limpiando..."
