

all:
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."
cliente:
	python3 cli5.py 127.0.0.1 12345 /etc/services
cliente_alternativo:
	python3 cli5.py 127.0.0.1 12345 /bin/sh
servidor:
	python3 serv5.py 127.0.0.1 12345
