all:
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."

test:
	javac -cp .;hamcrest-core-1.3.jar;C:\Users\jorge\practicaPED\kataencasa\junit-4.13.2.jar *.java
	java -cp .;hamcrest-core-1.3.jar;C:\Users\jorge\practicaPED\kataencasa\junit-4.13.2.jar org.junit.runner.JUnitCore Test_bolos
